name: build-image

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"
  pull_request:
    paths:
      - "Dockerfile"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v1.17.0, v1.18.0]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build the docker image and push
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 --tag ${{ secrets.DOCKERHUB_USERNAME }}/clash.meta:${{ matrix.version }} --build-arg META_VERSION=${{ matrix.version }} --file Dockerfile --push .
